SELECT
   C.CATEGORY_NAME,
   EXTRACT(MONTH FROM O.ORDER_DATE) AS Month,
   SUM(OD.QUANTITY * OD.UNIT_PRICE) AS Monthly_Sales_Value,
   SUM(SUM(OD.QUANTITY * OD.UNIT_PRICE)) OVER (PARTITION BY C.CATEGORY_NAME ORDER BY EXTRACT(MONTH FROM O.ORDER_DATE)) AS Cumulative_Sales_Value
FROM
   NORTHWIND.CATEGORIES C
INNER JOIN NORTHWIND.PRODUCTS P ON C.CATEGORY_ID = P.CATEGORY_ID
INNER JOIN NORTHWIND.ORDER_DETAILS OD ON P.PRODUCT_ID = OD.PRODUCT_ID
INNER JOIN NORTHWIND.ORDERS O ON OD.ORDER_ID = O.ORDER_ID
WHERE
   EXTRACT(YEAR FROM O.ORDER_DATE) = 2017
GROUP BY
   C.CATEGORY_NAME, EXTRACT(MONTH FROM O.ORDER_DATE)
ORDER BY
   C.CATEGORY_NAME, EXTRACT(MONTH FROM O.ORDER_DATE);