-- Retrieve sales total for the product "Chang" in category 1, grouped by category, product, and customer company
SELECT
   p.CATEGORY_ID,
   p.PRODUCT_NAME,
   c.COMPANY_NAME,
   TO_CHAR(SUM(d.QUANTITY * p.UNIT_PRICE), '$999,999.99') AS SALES_TOTAL
FROM
   (NORTHWIND.CUSTOMERS c
   INNER JOIN NORTHWIND.ORDERS o ON c.CUSTOMER_ID = o.CUSTOMER_ID)
   INNER JOIN
   (NORTHWIND.PRODUCTS p
   INNER JOIN NORTHWIND.ORDER_DETAILS d ON p.PRODUCT_ID = d.PRODUCT_ID)
   ON o.ORDER_ID = d.ORDER_ID
WHERE
   p.CATEGORY_ID = 1
   AND p.PRODUCT_NAME = 'Chang'
GROUP BY ROLLUP(p.CATEGORY_ID, p.PRODUCT_NAME, c.COMPANY_NAME)
ORDER BY 1, 2, 4 DESC;