-- Find the customer who received the highest total discount
SELECT
   c.CUSTOMER_ID,
   c.COMPANY_NAME,
   SUM(od.DISCOUNT) AS TOTAL_DISCOUNT
FROM
   NORTHWIND.ORDER_DETAILS od
JOIN
   NORTHWIND.ORDERS o ON od.ORDER_ID = o.ORDER_ID
JOIN
   NORTHWIND.CUSTOMERS c ON o.CUSTOMER_ID = c.CUSTOMER_ID
GROUP BY
   c.CUSTOMER_ID, c.COMPANY_NAME
ORDER BY
   TOTAL_DISCOUNT DESC
FETCH FIRST 1 ROWS ONLY;