-- Generate a summary of sales made by each employee in 2018
SELECT
   E.LASTNAME AS Employee_Lastname,
   E.FIRSTNAME AS Employee_Firstname,
   O.ORDER_DATE,
   OD.QUANTITY * OD.UNIT_PRICE AS Product_Value,
   SUM(OD.QUANTITY * OD.UNIT_PRICE) OVER (PARTITION BY E.LASTNAME, E.FIRSTNAME) AS Total_Sales
FROM
   NORTHWIND.EMPLOYEES E
JOIN NORTHWIND.ORDERS O ON E.EMPLOYEE_ID = O.EMPLOYEE_ID
JOIN NORTHWIND.ORDER_DETAILS OD ON O.ORDER_ID = OD.ORDER_ID
JOIN NORTHWIND.PRODUCTS P ON OD.PRODUCT_ID = P.PRODUCT_ID
WHERE
   EXTRACT(YEAR FROM O.ORDER_DATE) = 2018
ORDER BY
   1, 3;