-- Identify the three employees who served the fewest customers in the first quarter of 2017.
SELECT O.EMPLOYEE_ID,
      COUNT(O.CUSTOMER_ID) AS NUM_CUSTOMERS_SERVED,
      E.FIRSTNAME,
      E.LASTNAME
FROM NORTHWIND.ORDERS O
JOIN NORTHWIND.EMPLOYEES E ON O.EMPLOYEE_ID = E.EMPLOYEE_ID
WHERE O.ORDER_DATE >= TO_DATE('2017-01-01', 'YYYY-MM-DD')
AND O.ORDER_DATE < TO_DATE('2017-04-01', 'YYYY-MM-DD')
GROUP BY O.EMPLOYEE_ID,  E.FIRSTNAME, E.LASTNAME
ORDER BY NUM_CUSTOMERS_SERVED
FETCH FIRST 3 ROWS ONLY;