-- Calculate bonus for employees based on the number of orders they handled in 2017
SELECT
   E.LASTNAME,
   E.FIRSTNAME,
   COUNT(O.ORDER_ID) AS ORDER_COUNT,
   WIDTH_BUCKET(COUNT(O.ORDER_ID), 0, 100, 3) AS BUCKET,
   CASE
       WHEN WIDTH_BUCKET(COUNT(O.ORDER_ID), 0, 100, 3) = 1 THEN 500
       WHEN WIDTH_BUCKET(COUNT(O.ORDER_ID), 0, 100, 3) = 2 THEN 1000
       WHEN WIDTH_BUCKET(COUNT(O.ORDER_ID), 0, 100, 3) = 3 THEN 1500
   END AS BONUS
FROM
   NORTHWIND.EMPLOYEES E
LEFT JOIN NORTHWIND.ORDERS O ON E.EMPLOYEE_ID = O.EMPLOYEE_ID AND EXTRACT(YEAR FROM O.ORDER_DATE) = 2017
GROUP BY
   E.LASTNAME, E.FIRSTNAME
ORDER BY
   BUCKET;