-- Determine which employee had the most transactions in 2016
SELECT
   e.EMPLOYEE_ID,
   e.LASTNAME,
   e.FIRSTNAME,
   COUNT(*) AS TRANSACTION_COUNT
FROM
   NORTHWIND.ORDERS o
JOIN
   NORTHWIND.EMPLOYEES e ON o.EMPLOYEE_ID = e.EMPLOYEE_ID
WHERE
   EXTRACT(YEAR FROM o.ORDER_DATE) = 2016
GROUP BY
   e.EMPLOYEE_ID, e.LASTNAME, e.FIRSTNAME
ORDER BY
   TRANSACTION_COUNT DESC
FETCH FIRST 1 ROWS ONLY;