-- Find employees who earn the least and the most with division by years.
SELECT 
    EXTRACT(YEAR FROM e.HIREDATE) AS HIRED_YEAR,
    MIN(e.LASTNAME) AS MIN_SALARY_EMPLOYEE_LASTNAME,
    MIN(e.FIRSTNAME) AS MIN_SALARY_EMPLOYEE_FIRSTNAME,
    MAX(e.SALARY) AS MIN_SALARY,
    MAX(e.LASTNAME) AS MAX_SALARY_EMPLOYEE_LASTNAME,
    MAX(e.FIRSTNAME) AS MAX_SALARY_EMPLOYEE_FIRSTNAME,
    MIN(e.SALARY) AS MAX_SALARY
FROM 
    NORTHWIND.EMPLOYEES e
GROUP BY 
    EXTRACT(YEAR FROM e.HIREDATE);