-- Find the customer who purchased the highest quantity of a specific product
SELECT
   o.CUSTOMER_ID,
   c.COMPANY_NAME,
   od.PRODUCT_ID,
   p.PRODUCT_NAME,
   SUM(od.QUANTITY) AS TOTAL_QUANTITY
FROM
   NORTHWIND.ORDER_DETAILS od
JOIN
   NORTHWIND.ORDERS o ON od.ORDER_ID = o.ORDER_ID
JOIN
   NORTHWIND.CUSTOMERS c ON o.CUSTOMER_ID = c.CUSTOMER_ID
JOIN
   NORTHWIND.PRODUCTS p ON od.PRODUCT_ID = p.PRODUCT_ID
GROUP BY
   o.CUSTOMER_ID, c.COMPANY_NAME, od.PRODUCT_ID, p.PRODUCT_NAME
ORDER BY
   TOTAL_QUANTITY DESC
FETCH FIRST 1 ROWS ONLY;