-- Find products with less than the average quantity of beverages in stock
SELECT *
FROM NORTHWIND.PRODUCTS
WHERE UNITS_IN_STOCK < (SELECT AVG(UNITS_IN_STOCK) FROM NORTHWIND.PRODUCTS WHERE CATEGORY_ID = (SELECT CATEGORY_ID FROM NORTHWIND.CATEGORIES WHERE CATEGORY_NAME = 'Beverages'));