-- Pokaż, jak kształtuje się zysk ze sprzedaży w danym dniu miesiąca na przełomie wszystkich lat, które znajdują się w bazie.
SELECT
   EXTRACT(YEAR FROM ORDER_DATE) AS YEAR,
   EXTRACT(MONTH FROM ORDER_DATE) AS MONTH,
   EXTRACT(DAY FROM ORDER_DATE) AS DAY,
   SUM(FREIGHT) AS DAILY_PROFIT
FROM
   NORTHWIND.ORDERS
GROUP BY
   EXTRACT(YEAR FROM ORDER_DATE),
   EXTRACT(MONTH FROM ORDER_DATE),
   EXTRACT(DAY FROM ORDER_DATE)
ORDER BY
   EXTRACT(YEAR FROM ORDER_DATE),
   EXTRACT(MONTH FROM ORDER_DATE);