-- Determine the number of shipments handled by shipping companies, broken down by year
SELECT
   SHIP_NAME,
   EXTRACT(YEAR FROM o.SHIPPED_DATE) AS SHIP_YEAR,
   COUNT(*) AS TRANSACTION_COUNT
FROM
   NORTHWIND.ORDERS o
JOIN
   NORTHWIND.SHIPPERS s ON o.SHIP_VIA = s.SHIPPER_ID
WHERE
   o.SHIPPED_DATE IS NOT NULL
GROUP BY
   SHIP_NAME, EXTRACT(YEAR FROM o.SHIPPED_DATE)
ORDER BY
   SHIP_NAME, EXTRACT(YEAR FROM o.SHIPPED_DATE);