-- Find the top 3 employees by the total sales value of beverages in 2018
SELECT e.EMPLOYEE_ID,
       e.LastName,
       e.FirstName,
       SUM(od.UNIT_PRICE * od.Quantity) AS BeverageSales
FROM NORTHWIND.ORDERS o
JOIN NORTHWIND.ORDER_DETAILS od ON o.ORDER_ID = od.ORDER_ID
JOIN NORTHWIND.PRODUCTS p ON od.PRODUCT_ID = p.PRODUCT_ID
JOIN NORTHWIND.CATEGORIES c ON p.CATEGORY_ID = c.CATEGORY_ID
JOIN NORTHWIND.EMPLOYEES e ON o.EMPLOYEE_ID = e.EMPLOYEE_ID
WHERE c.CATEGORY_NAME = 'Beverages'
AND EXTRACT(YEAR FROM o.ORDER_DATE) = 2018
GROUP BY e.EMPLOYEE_ID, e.LastName, e.FirstName
ORDER BY BeverageSales DESC
FETCH FIRST 3 ROWS ONLY;