-- Retrieve transactions count and total sales value by year and employee position
SELECT
   EXTRACT(YEAR FROM O.ORDER_DATE) AS Transaction_Year,
   E.TITLE AS Employee_Position,
   COUNT(*) AS Transactions_Count,
   TO_CHAR(SUM(OD.QUANTITY * P.UNIT_PRICE), '$999,999.99') AS Total_Sales_Value
FROM
   NORTHWIND.ORDERS O
JOIN NORTHWIND.EMPLOYEES E ON O.EMPLOYEE_ID = E.EMPLOYEE_ID
JOIN NORTHWIND.ORDER_DETAILS OD ON O.ORDER_ID = OD.ORDER_ID
JOIN NORTHWIND.PRODUCTS P ON OD.PRODUCT_ID = P.PRODUCT_ID
GROUP BY
   ROLLUP(EXTRACT(YEAR FROM O.ORDER_DATE), E.TITLE)
ORDER BY
   Transaction_Year NULLS FIRST, Employee_Position NULLS FIRST;